// for resolve file by import statement
// https://github.com/Microsoft/TypeScript-React-Starter/issues/12#issuecomment-326370098
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.svg'
declare module '*.mp4'
declare module '*.webm'
declare module '*.ogg'
declare module '*.mp3'
declare module '*.wav'
declare module '*.flac'
declare module '*.aac'
declare module '*.woff2'
declare module '*.woff'
declare module '*.eot'
declare module '*.ttf'
declare module '*.otf'
